NETChallenge/Models/ErrorViewModel.cs
using System;

namespace NETChallenge.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

NETChallenge/Models/Url.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace NETChallenge.Models
{
    public class Url
    {
        /// <summary>
        ///     Primary key de la entidad
        /// </summary>
        [Key]
        public int Id { get; set; }

        /// <summary>
        ///     Url original
        /// </summary>
        public string OriginalUrl { get; set; }

        /// <summary>
        ///     Url corta
        /// </summary>
        public string ShortUrl { get; set; }

        /// <summary>
        ///     Fecha de creación
        /// </summary>
        public DateTime Fecha { get; set; }

        /// <summary>
        ///     username del usuario en sessión
        /// </summary>
        public string Usuario { get; set; }

        /// <summary>
        ///     Contador
        /// </summary>
        [NotMapped]
        public int Count { get; set; }

        /// <summary>
        ///     Propiedad de navegación hacia el detalle de la url
        /// </summary>
        public virtual List<UrlDetail> UrlDetails { get; set; }
    }
}

NETChallenge/Models/UrlDetail.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NETChallenge.Models
{
    public class UrlDetail
    {
        /// <summary>
        ///     Primary key
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        ///     Fecha de click de la url corta
        /// </summary>
        public DateTime Fecha { get; set; }

        /// <summary>
        ///     url id al que pertecen el detalle
        /// </summary>
        public int UrlId { get; set; }

        /// <summary>
        ///     Sistema operativo
        /// </summary>
        public string OS { get; set; }

        /// <summary>
        ///     Nombre del navegador
        /// </summary>
        public string Browser { get; set; }

        /// <summary>
        ///     Contador de clicks
        /// </summary>
        public int Count { get; set; }

        /// <summary>
        ///     Propiedad de navegación hacia Url
        /// </summary>
        public virtual Url Url { get; set; }

    }
}

NETChallenge/ViewModels/HomeViewModel.cs
using NETChallenge.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NETChallenge.ViewModels
{
    public class HomeViewModel
    {
        /// <summary>
        ///     Objeto de la nueva url corta a crear
        /// </summary>
        public Url NewUrl{ get; set; }

        /// <summary>
        ///     Listado de urls, se utilizaremos en la vista index del urlcontrller
        /// </summary>
        public List<Url> Urls { get; set; }
    }
}

NETChallenge/ViewModels/ShowViewModel.cs
using NETChallenge.DTO;
using NETChallenge.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NETChallenge.ViewModels
{
    public class ShowViewModel
    {
        public Url Url { get; set; }
        public List<MetricasDTO> DailyClicks { get; set; }
        public List<MetricasDTO> BrowseClicks { get; set; }
        public List<MetricasDTO> PlatformClicks { get; set; }
    }
}

NETChallenge/Controllers/API/ValuesController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using NETChallenge.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NETChallenge.Controllers.API
{
    [Route("api/[controller]")]
    [ApiController]
    public class ValuesController : ControllerBase
    {
        public IServiceUrl Service;
        public ValuesController(IServiceUrl service)
        {
            Service = service;
        }

        public async Task<JsonResult> Get()
        {
            return new JsonResult(new { data = await Service.GetAllAPI() });

        }
    }
}

NETChallenge/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using NETChallenge.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace NETChallenge.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

NETChallenge/Controllers/UrlsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using NETChallenge.Models;
using NETChallenge.Service;
using NETChallenge.ViewModels;
using Shyjus.BrowserDetection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NETChallenge.Controllers
{
    [Authorize]
    public class UrlsController : Controller
    {
        private readonly ILogger<UrlsController> _logger;
        private static readonly Random getrandom = new Random();
        private readonly IBrowserDetector browserDetector;
        private IServiceUrl ServiceUrl;

        public UrlsController(ILogger<UrlsController> logger, IBrowserDetector browserDetector, IServiceUrl serviceUrl)
        {
            this.browserDetector = browserDetector;
            _logger = logger;

            ServiceUrl = serviceUrl;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var model = new HomeViewModel
            {
                Urls = await ServiceUrl.GetAll(),
                NewUrl = new Url { Usuario = User.Identity.Name, Fecha = DateTime.Now },
            };
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Visit(string url)
        {

            // obtenemos la url por su token
            var urlResult = await ServiceUrl.GetByToken(url);
            if (urlResult is null) return NotFound();


            // registramos el click a la url
            await ServiceUrl.CountClick(urlResult);

            return Redirect(urlResult.OriginalUrl);

        }

        [HttpPost]
        public async Task<IActionResult> Create(HomeViewModel homeViewModel)
        {
            await ServiceUrl.Create(homeViewModel.NewUrl);
            return RedirectToAction(nameof(HomeController.Index));
        }

        [HttpGet]
        public async Task<IActionResult> Show(string url)
        {

            var urlResult = await ServiceUrl.GetByToken(url);

            return View(new ShowViewModel
            {
                Url = urlResult,
                DailyClicks = await ServiceUrl.GetDailyClick(urlResult.Id),
                BrowseClicks = await ServiceUrl.GetByBrowser(urlResult.Id),
                PlatformClicks = await ServiceUrl.GetByPlatforms(urlResult.Id),
            });

        }

    }
}

NETChallenge/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

NETChallenge/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NETChallenge</title>
    <link href="~/lib/materialize/css/materialize.css" rel="stylesheet" />
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">NETChallenge</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - NETChallenge - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/materialize/js/materialize.js"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

NETChallenge/Views/Urls/Index.cshtml
@model HomeViewModel

@{
    ViewData["Title"] = "Home Page";
}

@if (TempData["Notice"] is not null)
{
    <div class="card-panel notice deep-orange">@TempData["Notice"]</div>
}

<div class="row">
    <div class="col m12">
        <form asp-action="Create">
            <div class="card">
                <div class="card-content">
                    <div class="row">
                        <div class="col m8 offset-m2 center-align">
                            <span class="card-title">Create a new short URL</span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col m6 offset-m2">
                            <input asp-for="NewUrl.Usuario" type="hidden"/>
                            <input asp-for="NewUrl.Fecha" type="hidden"/>
                            <input type="text" class="validate form-control" placeholder="Your original URL here" asp-for="NewUrl.OriginalUrl"/>
                        </div>
                        <div class="col m2">
                            <button type="submit" class="btn">Shorten URL</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
<table class="table highlight">
    <thead>
        <tr>
            <th scope="col">Short URL</th>
            <th scope="col">Original URL</th>
            <th scope="col">Created</th>
            <th scope="col">Clicks Count</th>
            <th scope="col">Stats</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var url in Model.Urls)
        {
            <tr>
                <th scope="row"><a asp-controller="Urls" asp-action="Visit" asp-route-url="@url.ShortUrl" target="_blank">@url.ShortUrl</a></th>
                <td><a href="@url.OriginalUrl" target="_blank">@url.OriginalUrl</a></td>
                <td>@url.Fecha.ToShortDateString()</td>
                <td>@url.Count</td>
                <td>
                    <a asp-controller="Urls" asp-action="Show" asp-route-url="@url.ShortUrl">
                        <svg class="octicon octicon-graph" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true">
                            <path fill-rule="evenodd" d="M16 14v1H0V0h1v14h15zM5 13H3V8h2v5zm4 0H7V3h2v10zm4 0h-2V6h2v7z"></path>
                        </svg>
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

NETChallenge/Views/Urls/Show.cshtml
@model ShowViewModel

@{
    ViewBag.Title = "Show";
    Layout = "_Layout";
}

<div class="row">
    <div class="col s12">
        <ul class="card-panel collection with-header">
            <li class="collection-header">
                <h4>
                    Stats for <a href="@Model.Url.ShortUrl">@Model.Url.ShortUrl</a>
                </h4>
            </li>
            <li class="collection-item">Created May 22, 2021</li>
            <li class="collection-item">
                Original URL: https://drive.google.com/file/d/1VdLgSSMojWFb1GRoBAFX_eXy7oX2J
            </li>
        </ul>
    </div>
</div>

<div class="row">
    <div class="col s12">
        <div class="card-panel">
            <div id="total-clicks-chart"></div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col s6">
        <div class="card-panel">
            <div id="platforms-chart"></div>
        </div>
    </div>

    <div class="col s6">
        <div class="card-panel">
            <div id="browsers-chart"></div>
        </div>
    </div>
</div>

<script>
    google.charts.load('current', {packages: ['corechart']});
    google.charts.setOnLoadCallback(drawCharts);
    function drawTotalClicksChart() {
      var data = google.visualization.arrayToDataTable([
        ['day', 'clicks'],
      ].concat(@Json.Serialize(Model.DailyClicks.Select(e => new object[] { e.Key, e.Value }))));
      var options = {
        title: 'total clicks',
        haxis: {
          title: 'day of month'
        },
        vaxis: {
          title: 'clicks'
        }
      };
      var chart = new google.visualization.AreaChart(
        document.getElementById('total-clicks-chart')
      );
      chart.draw(data, options);
    }
    function drawBrowsersChart() {
      var data = google.visualization.arrayToDataTable([
        ['browser', 'clicks'],
      ].concat(@Json.Serialize(Model.BrowseClicks.Select(e => new object[] { e.Key, e.Value }))));
      var options = {
        title: 'Browsers'
      };
      var chart = new google.visualization.PieChart(
        document.getElementById('browsers-chart')
      );
      chart.draw(data, options);
    }
    function drawPlatformsChart() {
      var data = google.visualization.arrayToDataTable([
        ['platform', 'clicks'],
      ].concat(@Json.Serialize(Model.PlatformClicks.Select(e => new object[] { e.Key, e.Value }))));
      var options = {
        title: 'Platform'
      };
      var chart = new google.visualization.PieChart(
        document.getElementById('platforms-chart')
      );
      chart.draw(data, options);
    }
    function drawCharts() {
      drawTotalClicksChart();
      drawBrowsersChart();
      drawPlatformsChart();
    }
</script>